// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the MyFirstModule module
	public static myfirstmodule.proxies.TestEntity dS_TestEntity(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("MyFirstModule.DS_TestEntity").withParams(params).execute(context);
		return result == null ? null : myfirstmodule.proxies.TestEntity.initialize(context, result);
	}
	public static void wDG_JsonEditor_OnChange(IContext context, myfirstmodule.proxies.TestEntity _testEntity)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TestEntity", _testEntity == null ? null : _testEntity.getMendixObject());
		Core.microflowCall("MyFirstModule.WDG_JsonEditor_OnChange").withParams(params).execute(context);
	}
}
